// Generated by https://quicktype.io

export interface Notes {
    data: Note[];
    page: Page;
    pagination: Pagination;
}

export interface Note {
    noteID: string;
    title: string;
    body: string;
    customerId: string;
    category: Category;
    createdAt: string;
    updatedAt: string;
    id: string;
}

export enum Category {
    Other = 'Other',
    Personal = 'Personal',
    Study = 'Study',
    Work = 'Work',
}

export interface Page {
    current: number;
    next: number;
    limit: number;
}

export interface Pagination {
    next: string;
    prev: null;
}
